{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ default "1h" .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ default "SecretStore" .Values.externalSecret.secretStore.kind | quote }}
    name: {{ required "secret store name is a required field" .Values.externalSecret.secretStore.name | quote }}
  target:
    name: {{ .Release.Name }}-externalsecret-data
    creationPolicy:  "Owner"
  data:
  {{- range $data := .Values.externalSecret.data}}
  {{- range $property := $data.properties }}
    - secretKey: {{ $property | quote }}
      remoteRef:
        key: {{ $data.key | quote }}
        property: {{ $property | quote }}
  {{- end }}
  {{- end }}

  dataFrom:
  {{- range $data := .Values.externalSecret.data }}
  {{- if not (hasKey $data "properties") }}
  - extract:
      key: {{ $data.key | quote }}
  {{- end }}
  {{- end }}
{{- end }}
