{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name | default (printf "%s-pvc" (include "ai-module.fullname" .)) }}
  labels:
    {{- include "ai-module.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  {{- with .Values.pvc.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
